site_name: D4RL Slim Benchmark
site_description: Code for benchmarking D4RL-slim

repo_url: https://github.com/dtch1997/d4rl-slim-benchmark
repo_name: dtch1997/d4rl-slim-benchmark

theme:
    name: material
    icon:
        logo: material/library
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: red
          accent: red
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: red
          accent: red
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                import:
                    - https://docs.python.org/3.10/objects.inv
                options:
                    docstring_style: google

watch:
    - docs
    - d4rl_slim_benchmark

nav:
    - About: index.md
    - Reference:
        - d4rl_slim_benchmark: reference/d4rl_slim_benchmark.md
